version: "3"

services:
  db:
    build: "./db"
    volumes:
      - "./db/data:/var/lib/mysql"
      - "./db/scripts:/tests"
    ports:
      - "3307:3306"
    env_file:
      - "./db/.env"
    environment:
      - TZ=Asia/Bangkok
      - LANG=C.UTF-8

  backend:
    build:
      context: "./backend"
    ports:
      - "8080:8080"
    depends_on:
      - db
    env_file:
      - "./backend/.env"
    restart: on-failure
    environment:
      - MYSQL_USER=us3admin
      - MYSQL_HOST=db
      - MYSQL_PORT=3306
      - MYSQL_DATABASE=oasip

  nginx:
    build:
      context: "./frontend"
      args:
        - VITE_API_URL=http://ip21us3.sit.kmutt.ac.th:8080/api
    ports:
      - "80:80"
    depends_on:
      - backend
