version: "3"

services:
  db:
    build: "./db"
    volumes:
      - "./db/data:/var/lib/mysql"
      - "./db/scripts:/tests"
    ports:
      - "3306:3306"
    env_file:
      - "./db/.env"
    environment:
      - TZ=Asia/Bangkok
      - LANG=C.UTF-8

  backend:
    build:
      context: "./backend"
    depends_on:
      - db
    env_file:
      - "./backend/.env"
    restart: on-failure
    environment:
      - MYSQL_USER=us3admin
      - MYSQL_HOST=db
      - MYSQL_PORT=3306
      - MYSQL_DATABASE=oasip

  frontend:
    build:
      context: "./frontend"
      args:
        - VITE_API_URL=/us3/api
        - BASE_URL=/us3
    depends_on:
      - backend

  nginx:
    build: "./nginx"
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend