name: CD OMEGALUL

on:
  workflow_dispatch:
    inputs:
      db:
        description: Build and push DB image
        type: boolean
        required: false
      backend:
        description: Build and push backend image
        type: boolean
        required: false
      frontend:
        description: Build and push frontend image
        type: boolean
        required: false
      reverse_proxy:
        description: Build and push reverse proxy image
        type: boolean
        required: false
  push:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest
    name: Build and push Docker images
    steps:
      - uses: actions/checkout@v2
      - id: changes
        uses: dorny/paths-filter@v2
        with:
          filters: |
            db:
              - 'db/**'
            backend:
              - 'backend/**'
            frontend:
              - 'frontend/**'
            reverse_proxy:
              - 'reverse_proxy/**'
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to GitHub Packages
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - id: string
        uses: ASzc/change-string-case-action@v1
        with:
          string: ${{ github.repository }}

      - name: DB image
        if: steps.changes.outputs.db == 'true' || github.event.inputs.db == 'true'
        uses: docker/build-push-action@v3
        with:
          push: true
          context: ./db
          tags: ghcr.io/${{ steps.string.outputs.lowercase }}/db:latest

      - name: Backend image
        if: steps.changes.outputs.backend == 'true' || github.event.inputs.backend == 'true'
        uses: docker/build-push-action@v3
        with:
          push: true
          context: ./backend
          tags: ghcr.io/${{ steps.string.outputs.lowercase }}/backend:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Frontend image
        if: steps.changes.outputs.frontend == 'true' || github.event.inputs.frontend == 'true'
        uses: docker/build-push-action@v3
        with:
          push: true
          context: ./frontend
          build-args: |
            VITE_API_URL=/us3/api
            BASE_URL=/us3
          tags: ghcr.io/${{ steps.string.outputs.lowercase }}/frontend:latest

      - name: Reverse proxy image
        if: steps.changes.outputs.reverse_proxy == 'true' || github.event.inputs.reverse_proxy == 'true'
        uses: docker/build-push-action@v3
        with:
          push: true
          context: ./reverse_proxy
          tags: ghcr.io/${{ steps.string.outputs.lowercase }}/reverse_proxy:latest
