name: DB CD OMEGALUL

on:
  workflow_dispatch:
  push:
    paths:
      - "db/**"

jobs:
  docker:
    runs-on: ubuntu-latest
    name: Build and push Docker image
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login to GitHub Packages
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          context: ./db
          tags: ghcr.io/${{ github.repository }}/db:latest
          
